### ISSUE TITLE
request for some event switches for Subversion

### ISSUE THREAD

**Issue by beauxq** [InsaneFirebat/sm_practice_hack#14]
For Super Metroid Subversion, these would be some of the most useful events to be able to toggle:

- event `1D` crash space port
- event `1F` power off

**Comment by InsaneFirebat** [comment]
Thanks. Are those the names you'd want to use on the toggles?

**Comment by beauxq** [comment]
Yeah, I think those names would be good. The power one might be confusing, because I think 0 is power on, and 1 is power off. But I'm not sure about that.
If the name of the switch is "power off", it'll probably be fine. People will figure it out.
Or you could call it "power" and swap the 1 and 0 for off and on? I don't know.

**Comment by InsaneFirebat** [comment]
What area is the power for? Inverting the toggle (swapping 1/0 behavior) is no problem if that makes more sense.

**Comment by beauxq** [comment]
The power has effects all over lots of areas. It's not just limited to one area.

**Comment by beauxq** [comment]
If you're wanting to test it. The west corridor save station will let you see the effects nearby.

**Comment by InsaneFirebat** [comment]
The new events are added and patches for v2.5.10.1 are in the `releases` folder. Thanks for the request and info.

**Comment by beauxq** [comment]
thank you
